pipeline:
    name: helloWorld
    identifier: helloWorld
    projectIdentifier: DougGitExpExample
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: douglasjbothwellgithub
                repoName: codebaseBeta
                build: <+input>
    stages:
        - stage:
              name: helloworld
              identifier: helloworld
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.docexample
                          namespace: default
                          automountServiceAccountToken: true
                          nodeSelector: {}
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: example
                                identifier: example
                                spec:
                                    connectorRef: account.harnessImage
                                    image: alpine:latest
                                    shell: Sh
                                    command: echo test
